FROM bioconductor/bioconductor_docker:RELEASE_3_13

LABEL SOFTWARE_NAME R 4.0.x with Bioconductor 3.13
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "Bioconductor 3.13"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN     apt-get clean && \
        rm -r /var/lib/apt/lists/*

RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && apt-get upgrade -y --fix-missing

RUN     apt-get update && apt-get install -y  --no-install-recommends \
            build-essential

RUN     Rscript -e "options(Ncpus=8); \
            BiocManager::install(c( \
                'adegenet', \
                'apeglm', \
                'ashr', \
                'Biostrings', \
                'dada2', \
                'DESeq2', \
                'future.apply', \
                'GenomicAlignments', \
                'GenomicFeatures', \
                'GenomicRanges', \
                'Gviz', \
                'Mfuzz', \
                'pheatmap', \
                'phyloseq', \
                'rehh', \
                'rtracklayer', \
                'ShortRead', \
                'SNPRelate', \
                'systemPipeR', \
                'tximport', \
                'tximeta', \
                'valr', \
                'VariantAnnotation', \
                'vcfR' \
                ), \
            type='source', ask=FALSE)"


ENTRYPOINT ["/usr/local/bin/R"]